<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!--
    Cyber Brief HTML template (Documentation/Templates as code).
    Placeholders use {{MUSTACHE}} style and are filled by the cyber-brief
    workflow's render node. This same content drives the PDF and email versions.
    Keep it self-contained (inline CSS) so it renders consistently in email
    clients and headless PDF renderers.
  -->
  <title>Cyber Brief — {{DATE}}</title>
  <style>
    body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #1a1a1a; max-width: 820px; margin: 0 auto; padding: 24px; line-height: 1.5; }
    header { border-bottom: 3px solid #0b5; padding-bottom: 12px; margin-bottom: 20px; }
    h1 { font-size: 22px; margin: 0; }
    .meta { color: #666; font-size: 13px; }
    h2 { font-size: 17px; margin-top: 28px; border-left: 4px solid #0b5; padding-left: 10px; }
    .severity-high { color: #b00; font-weight: 600; }
    .severity-medium { color: #c70; font-weight: 600; }
    .severity-low { color: #393; font-weight: 600; }
    footer { margin-top: 32px; border-top: 1px solid #ddd; padding-top: 12px; color: #888; font-size: 12px; }
    pre { white-space: pre-wrap; }
  </style>
</head>
<body>
  <header>
    <h1>🛡️ Cyber Threat Intelligence Brief</h1>
    <div class="meta">{{DATE}} · Region focus: {{REGION_FOCUS}} · Generated by Jarvis</div>
  </header>

  <main>
    <!-- The analyst output (Markdown rendered to HTML) is injected here. -->
    {{CONTENT}}
  </main>

  <footer>
    Produced automatically from open intelligence sources. Verify critical
    findings against primary advisories before acting. Historical briefs are
    archived under reports/archive.
  </footer>
</body>
</html>
